# Generated by Django 5.1.2 on 2024-11-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_entry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.entry')),
            ],
        ),
    ]
