# Generated by Django 5.1.2 on 2024-11-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.topic'),
        ),
    ]
