# Generated by Django 5.1.2 on 2024-11-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_photo_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
