# Generated by Django 5.1.2 on 2024-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_entry_image_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, default='django.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default='django.png', upload_to='images/'),
        ),
    ]
