# Generated by Django 5.1.2 on 2024-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_alter_entry_image_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, default='django.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default='django.png', upload_to=''),
        ),
    ]
